name: TimeRank
main: com.oberonserver.timerank.timerank
version: 0.1.0
commands:
    playtime:
        description: Displays current play time of a player.
        usage: /playtime <player>
    listranks:
        description: List ranks and there requirements
        usage: /listranks <filter>
    buyrank:
        description: Buy a listed rank
        usage: /buyrank <rank>
    rentrank:
        description: Rents a listed rank
        usage: /rentrank <rank>
    listabs:
        description: List ranks and there requirements
        usage: /listabs <filter>
    buyab:
        description: Buy a listed ability
        usage: /buyab <ability>
    rentab:
        description: Rents a listed ability
        usage: /rentab <ability>
    checkranks:
        description: Check ranks and promote if needed
        usage: /checkranks
    timerank:
        description: Controles the timerank plugin
        usage: /timerank <command>
    